[project]
name = "log-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "pytz>=2025.2",
    "uvicorn>=0.35.0",
]
